//
//  JobRequestWorker.swift
//  DriveTime
//
//  Created by Wing Sun Cheung on 9/18/18.
//  Copyright (c) 2018 Wing Sun Cheung. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
import AlamofireObjectMapper

enum JobRequestError: Error {
    case FailedToFetchJobRequests
}

class JobRequestWorker {
    
    private let JOB_REQUEST_BASE_URL = "https://drivetimepro1.000webhostapp.com/apps/android/readRequests.php?"
    
    private let ACCEPT_JOB_REQUEST_BASE_URL = "https://drivetimepro1.000webhostapp.com/apps/android/acceptRequests.php?"
    
    func fetchJobRequests(email: String?, completionHandler: @escaping (JobRequest.fetchJobRequest.Response?, JobRequestError?) -> Void) {
        
        guard let email = email else {
            return
        }
        
        // This id number only pulls 0 - 1000 job requests, if we need more, we need to iterate at 1000 steps 
        
        let id = 0
        
        let parameter = [
            "id" : id.toString(),
            "username" : email
        ]
        
        Alamofire.request(JOB_REQUEST_BASE_URL, method: .get, parameters: parameter, encoding: URLEncoding(), headers: nil).responseArray { (response: DataResponse<[JobResponseDataObject]>) in
            
            log.debug("Fetching Job Requests...")
            
            switch response.result {
                
            case .success(let responseArray) :
                log.debug("Sucessfully fetch job requests")
                log.debug("Job request counts: \(responseArray.count)")
                completionHandler(JobRequest.fetchJobRequest.Response(jobResponses: responseArray), nil)
                
            case .failure(let error) :
                
                log.debug("Fetching error: JobRequest")
                log.debug(error.localizedDescription)
                completionHandler(nil, .FailedToFetchJobRequests)
                
            }
        }
    }
    
    func acceptJobRequest(jobRequestObject: JobResponseDataObject?, email: String?) -> Bool{
        
        var isAccepted = false
        
        guard let jobRequestObject = jobRequestObject else {
            return isAccepted
        }
        
        // MARK: - This needs to be mapped to unoptional dictionary
        
        let parameters: [String :String] = [
            
            "id"                : jobRequestObject.id!,
            "client_email"      : jobRequestObject.clientEmail!,
            "client_name"       : jobRequestObject.clientName!,
            "business"          : jobRequestObject.business!,
            "details"           : jobRequestObject.detail!,
            "amount_offered"    : jobRequestObject.amountOffered!,
            "driver_email"      : email!
        ]
        

        Alamofire.request(ACCEPT_JOB_REQUEST_BASE_URL, method: .get, parameters: parameters, encoding: URLEncoding(), headers: nil).responseString { (response) in
            isAccepted = true
        }
        
        return isAccepted
 
    }
    
}

extension Int {
    func toString() -> String {
        return ("\(self)")
    }
}




