//
//  LoginWorker.swift
//  DriveTime
//
//  Created by Wing Sun Cheung on 8/1/18.
//  Copyright (c) 2018 Wing Sun Cheung. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
import AlamofireObjectMapper

enum LoginError: Error {
    
    case incompleteField
    case incorrectUsernameOrPassword
    case noNetworkConnection
}

class LoginWorker {

    private let BASE_URL = "https://drivetimepro1.000webhostapp.com/apps/android/loginDriver.php?"
    private let USERNAME_PARAM = "login_name"
    private let PASSWORD_PARAM = "login_pass"
    
    func fetchUserData(payload: Login.FetchUserData.Request, completionHandler: @escaping (Login.FetchUserData.Response?, LoginError?) -> Void) {
        
        let reachablity = NetworkReachabilityManager();
        
        guard let isConnected = reachablity?.isReachable, isConnected != false else {
            completionHandler(nil, .noNetworkConnection)
            return
        }
        
        guard let email = payload.email, !email.isEmpty, let password = payload.password, !password.isEmpty else {
            completionHandler(nil, .incompleteField)
            return
        }
        
        let parameter: [String: String] = [USERNAME_PARAM: email, PASSWORD_PARAM: password]
        
        Alamofire.request(BASE_URL, method: .post, parameters: parameter, encoding: URLEncoding(), headers: nil).responseArray { (response: DataResponse<[LoginDataObject]>) in
            
            let result = response.result
            
            switch result {
                
            case .success(let responseArray) :
                completionHandler(Login.FetchUserData.Response(userProfile: responseArray), nil)

            case .failure(let error) :
                completionHandler(nil, .incorrectUsernameOrPassword)
                
            }
        }
    }
}



















