//
//  LoginInteractor.swift
//  DriveTime
//
//  Created by Wing Sun Cheung on 8/1/18.
//  Copyright (c) 2018 Wing Sun Cheung. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic {
    func fetchLoginData(request: Login.FetchUserData.Request)
}

class LoginInteractor: LoginBusinessLogic {
    
    var presenter: LoginPresentationLogic?
    var worker: LoginWorker?
    
    func fetchLoginData(request: Login.FetchUserData.Request) {
        
        worker = LoginWorker()
        
        worker?.fetchUserData(payload: request, completionHandler: { [unowned self] (data, errors) in
            
            if let error = errors {
                log.debug("User profile error while fetching")
                self.presenter?.presentFailedLoginDialogue(loginError: error)
            }
            
            if let response = data {
                log.debug("User profile successfully fetched")
                self.presenter?.presentFetchedResults(response: response)
            }
        })
    }
}














