
//  LoginRouter.swift
//  DriveTime
//
//  Created by Wing Sun Cheung on 8/1/18.
//  Copyright (c) 2018 Wing Sun Cheung. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
    func routeToUserProfile(segue: UIStoryboardSegue?)
    func routeToSignUpForm(segue: UIStoryboardSegue?)
}

protocol LoginDataPassing
{
  var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    func routeToSignUpForm(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! SignUpViewController
            navigateToSignUpForm(source: viewController!, destination: destinationVC)
        }
    }
    
    func routeToUserProfile(segue: UIStoryboardSegue?) {
        
    }
    
    func navigateToSignUpForm(source: LoginViewController, destination: SignUpViewController)
    {
        source.show(destination, sender: nil)
    }

  // MARK: Routing

//  func routeToSomewhere(segue: UIStoryboardSegue?)
//  {
//    if let segue = segue {
//      let destinationVC = segue.destination as! UserProfileViewController
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//    } else {
//      let storyboard = UIStoryboard(name: "Main", bundle: nil)
//      let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//      navigateToSomewhere(source: viewController!, destination: destinationVC)
//    }
//  }
//
//  // MARK: Navigation
//
//
//
//  // MARK: Passing data
//
//  func passDataToSomewhere(source: LoginDataStore, destination: inout SomewhereDataStore)
//  {
//    destination.name = source.name
//  }
}
