//
//  LoginPresenter.swift
//  DriveTime
//
//  Created by Wing Sun Cheung on 8/1/18.
//  Copyright (c) 2018 Wing Sun Cheung. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func presentFetchedResults(response: Login.FetchUserData.Response)
    func presentFailedLoginDialogue(loginError: LoginError)
}

class LoginPresenter: LoginPresentationLogic {
    
    weak var viewController: LoginDisplayLogic?
    
    func presentFetchedResults(response: Login.FetchUserData.Response) {
        
        guard let userProfile = response.userProfile else {
            return
        }
        
        let viewModel = Login.FetchUserData.ViewModel(response: userProfile)
        viewController?.presentSuccessLoginDialog(viewModel: viewModel)
    }
    
    func presentFailedLoginDialogue(loginError: LoginError) {
        
        var message: String = ""
        
        switch loginError {
            
        case .incompleteField :
            log.debug("Please provide username and password")
            message = "Please provide username and password"
            
        case .incorrectUsernameOrPassword :
            log.debug("Incorrect username or password, please try again")
            message = "Incorrect username or password, please try again"
            
        case .noNetworkConnection :
            log.debug("No internet connected detected")
            message = "No internet connected detected"
        }
        viewController?.presentLoginErrorDialog(error: message)
    }
}







