//
//  LoginInteractor.swift
//  DriveTime
//
//  Created by Wing Sun Cheung on 8/1/18.
//  Copyright (c) 2018 Wing Sun Cheung. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic {
    func fetchLoginData(request: Login.FetchUserData.Request)
}

protocol LoginDataStore {
    //var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore {
    
    var presenter: LoginPresentationLogic?
    var worker: LoginWorker?
    
    func fetchLoginData(request: Login.FetchUserData.Request) {
        
        worker = LoginWorker()
        
        worker?.fetchUserData(payload: request, completionHandler: { [unowned self] (data, errors) in
            
            if let error = errors {
                switch error {
                    
                case .incompleteField :
                    log.debug("No username or password provided")
                    self.presenter?.presentFailedLoginDialogue(message: "Please provide username and password")
                    
                case .incorrectUsernameOrPassword :
                    log.debug("Incorrect username or password")
                    self.presenter?.presentFailedLoginDialogue(message: "Incorrect username or password, please try again")
                    
                case .noNetworkConnection :
                    log.debug("No network is present")
                    self.presenter?.presentFailedLoginDialogue(message: "No internet connected detected")
                }
            }
            
            if let response = data {
                log.debug("User profile successfully fetched")
                self.presenter?.presentFetchedResults(response: response)
                
            }
            

            
        })
    }
}

//            let clientName: String
//            let businessName: String
//            let clientEmailAddress: String
//            let driverEmailAddress: String























































