//
//  LoginWorker.swift
//  DriveTime
//
//  Created by Wing Sun Cheung on 8/1/18.
//  Copyright (c) 2018 Wing Sun Cheung. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
import AlamofireObjectMapper

enum LoginError: Error {
    
    case incompleteField
    case incorrectUsernameOrPassword
    case noNetworkConnection
}

class LoginWorker {
    
    private let BASE_URL = "https://www.prodrivetime.com/api/mobileApi/mobileDriverLogin"
    private let USERNAME_PARAM = "email"
    private let PASSWORD_PARAM = "password"
    
    func fetchUserData(payload: Login.FetchUserData.Request, completionHandler: @escaping (Login.FetchUserData.Response?, LoginError?) -> Void) {
        
        let reachablity = NetworkReachabilityManager();
        
        guard let isConnected = reachablity?.isReachable, isConnected != false else {
            completionHandler(nil, .noNetworkConnection)
            return
        }
        
        guard let email = payload.email, !email.isEmpty, let password = payload.password, !password.isEmpty else {
            completionHandler(nil, .incompleteField)
            return
        }
        
        let parameter: [String: String] = [USERNAME_PARAM: email, PASSWORD_PARAM: password]
        log.debug(parameter)
        
        Alamofire.request(BASE_URL, method: .post, parameters: parameter, encoding: URLEncoding(), headers: nil).responseObject { (response: DataResponse<LoginDataObject>) in
            log.debug(response)
            
            let result = response.result
            
            switch result {
                
            case .success(let response):
                log.debug("Login success")
                completionHandler(Login.FetchUserData.Response(userProfile: response), nil)
                
            case .failure(let error) :
                
                log.debug("Login failed")
                log.debug(error.localizedDescription)
                completionHandler(nil, .incorrectUsernameOrPassword)
                
                
            }
        }
        
    }
}




















