//
//  LoginModels.swift
//  DriveTime
//
//  Created by Wing Sun Cheung on 8/1/18.
//  Copyright (c) 2018 Wing Sun Cheung. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Login {
    
    struct FetchUserData {
        
        struct Request {
            let email: String?
            let password: String?
        }
        
        struct Response {
            var userProfile: LoginDataObject?
        }
        
        struct ViewModel {
            
            var name: String?
            var email: String?
            var number: String?
            var city: String?
            var experience: String?
            
            init(response: LoginDataObject) {
                self.name = response.name
                self.email = response.email
                self.number = response.number
                self.city = response.city
                self.experience = response.experience
            }
        }
    }
}


// JSON response
//
//"id": "29",
//"client_email": "trucking@gmail.com",
//"client_name": "Some Guy",
//"business": "Trucking.co",
//"details": "dshghsdggugyfjgdufhgcsgdgbv csdkjjhfdvsmnhdhgbjhdsndbs",
//"amount_offered": "3000",
//"driveremail": "",
//"timestamp": "2018-06-24 19:13:05"


