//
//  SignUpModels.swift
//  DriveTime
//
//  Created by Wing Sun Cheung on 8/18/18.
//  Copyright (c) 2018 Wing Sun Cheung. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct SignUp {

  
  struct RegisterNewUser {
    
    struct Request {
        var name: String?
        var email: String?
        var number: String?
        var password: String?
        var cdl: String?
        var city: String?
        var experience: String?
        
    }
    
    struct Response {
        
        
        
        
    }
    
    struct ViewModel {
        
        
        
    }
  }
}
