//
//  SignUpInteractor.swift
//  DriveTime
//
//  Created by Wing Sun Cheung on 8/18/18.
//  Copyright (c) 2018 Wing Sun Cheung. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpBusinessLogic {
  func performRegistration(request: SignUp.RegisterNewUser.Request)
}

protocol SignUpDataStore {
  //var name: String { get set }
}

class SignUpInteractor: SignUpBusinessLogic, SignUpDataStore {

    
  var presenter: SignUpPresentationLogic?
  var worker: SignUpWorker?
  
  func performRegistration(request: SignUp.RegisterNewUser.Request) {

    worker = SignUpWorker()
    worker?.performRegistration(request: request)
    
    let response = SignUp.RegisterNewUser.Response()
    presenter?.presentSomething(response: response)
  }
}
