//
//  SignUpWorker.swift
//  DriveTime
//
//  Created by Wing Sun Cheung on 8/18/18.
//  Copyright (c) 2018 Wing Sun Cheung. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class SignUpWorker{
    
    private let SIGN_UP_BASE_URL = "https://drivetime.000webhostapp.com/test/add_info.php"
    
  func performRegistration(request: SignUp.RegisterNewUser.Request) {
    
    let parameters: [String: String] = [
        "email"         : request.email!,
        "number"        : request.number!,
        "password"      : request.password!,
        "cdl"           : request.cdl!,
        "city"          : request.city!,
        "experience"    : request.experience!
    ]
    
    Alamofire.request(SIGN_UP_BASE_URL, method: .post, parameters: parameters, encoding: URLEncoding(), headers: nil).response { (response) in
        
        log.debug(response)
        
    }
    
    
  }
    
    
}
